version: '3'
services:
  db:
    image: postgres:10
    env_file: .env
    ports:
      - ${DB_PORT}:${DB_PORT}

  api:
    image: node:8.7
    working_dir: /api
    command: ["./wait-for-it.sh", "${DB_HOST}:${DB_PORT}", "--", "./init-backend.sh"]
    ports:
      - ${API_PORT}:${API_PORT}
    env_file: .env
    volumes: 
      - .:/api
    depends_on:
      - db
